default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: docuseal_dev

test:
  <<: *default
  database: docuseal_test

<% if ENV['DATABASE_URL'].to_s.empty? %>
production:
  adapter: sqlite3
  database: <%= ENV['WORKDIR'] || '.' %>/db.sqlite3
<% end %>
