default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: docuseal_dev

test:
  <<: *default
  database: docuseal_test

production:
  adapter: <%= ENV['DATABASE_URL'].present? ? 'postgresql' : 'sqlite3' %>
  encoding: unicode
  database: <%= ENV['WORKDIR'] || '.' %>/db.sqlite3
